dist: xenial
sudo: required
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt update
  - sudo apt install -y libuv1-dev bison flex 
script: 
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DATHDNS_ENABLE_TESTING=ON
  - make VERBOSE=1
after_success:
  - tests/dnstest
branches:
  only:
    - master
notifications:
  email: false
addons:
  apt:
    update: true
