dist: xenial
sudo: required
language: cpp
sudo: required
compiler:
  - gcc
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages: libuv1-dev bison flex lcov libmbedtls-dev libssl-dev gcc-7 g++-7 libnghttp2-dev
before_install:
    - export CXX="g++-7" CC="gcc-7"
script: 
  - scripts/build.sh
after_success:
  - scripts/upload.bash
branches:
  only:
    - master
    - develop
notifications:
  email: false
