dist: xenial
sudo: required
language: cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    packages: libuv1-dev bison flex lcov libmbedtls-dev libssl-dev nodejs npm
script: 
  - scripts/build.sh
after_success:
  - scripts/upload.bash
branches:
  only:
    - master
notifications:
  email: false
